[package]
name = "htmlfile"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
