[package]
name = "logging"
version = "0.1.0"
edition = "2021"

assets = ["pages/*"]

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing-subscriber = { workspace = true }